/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CikisRouteImport } from './routes/cikis'
import { Route as CronRouteImport } from './routes/cron'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as HakkimdaRouteImport } from './routes/hakkimda'
import { Route as HizmetlerRouteImport } from './routes/hizmetler'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as RandevuRouteImport } from './routes/randevu'
import { Route as SifremiUnuttumRouteImport } from './routes/sifremi-unuttum'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAsistanRouteImport } from './routes/admin.asistan'
import { Route as AdminBildirimlerRouteImport } from './routes/admin.bildirimler'
import { Route as AdminDanisanlarRouteImport } from './routes/admin.danisanlar'
import { Route as AdminExportRouteImport } from './routes/admin.export'
import { Route as AdminGoruslerRouteImport } from './routes/admin.gorusler'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMaliRouteImport } from './routes/admin.mali'
import { Route as AdminPaketlerRouteImport } from './routes/admin.paketler'
import { Route as AdminRandevularRouteImport } from './routes/admin.randevular'
import { Route as AdminSifrelerRouteImport } from './routes/admin.sifreler'
import { Route as AdminTahlillerRouteImport } from './routes/admin.tahliller'
import { Route as AdminTelegramRouteImport } from './routes/admin.telegram'
import { Route as AsistanGirisRouteImport } from './routes/asistan.giris'
import { Route as PanelIndexRouteImport } from './routes/panel.index'
import { Route as PanelMesajRouteImport } from './routes/panel.mesaj'
import { Route as PanelProfilRouteImport } from './routes/panel.profil'
import { Route as PanelSifreRouteImport } from './routes/panel.sifre'
import { Route as RandevuIndexRouteImport } from './routes/randevu.index'
import { Route as RandevuBasariliRouteImport } from './routes/randevu.basarili'
import { Route as AdminDanisanIdRouteImport } from './routes/admin.danisan.$id'
import { Route as AdminDanisanEkleRouteImport } from './routes/admin.danisan.ekle'
import { Route as ApiV1AuthLogoutRouteImport } from './routes/api/v1/auth/logout'
import { Route as ApiV1AuthMeRouteImport } from './routes/api/v1/auth/me'
import { Route as ApiV1ClientDailyRouteImport } from './routes/api/v1/client/daily'
import { Route as ApiV1ClientFastingRouteImport } from './routes/api/v1/client/fasting'
import { Route as ApiV1ClientLabsRouteImport } from './routes/api/v1/client/labs'
import { Route as ApiV1ClientMessagesRouteImport } from './routes/api/v1/client/messages'
import { Route as ApiV1ClientMindfulRouteImport } from './routes/api/v1/client/mindful'
import { Route as ApiV1ClientOffplanRouteImport } from './routes/api/v1/client/offplan'
import { Route as ApiV1ClientPanelRouteImport } from './routes/api/v1/client/panel'
import { Route as ApiV1ClientPasswordRouteImport } from './routes/api/v1/client/password'
import { Route as ApiV1ClientProfileRouteImport } from './routes/api/v1/client/profile'
import { Route as ApiV1ClientWaterRouteImport } from './routes/api/v1/client/water'
import { Route as ApiV1StaffAppointmentsRouteImport } from './routes/api/v1/staff/appointments'
import { Route as ApiV1StaffDashboardRouteImport } from './routes/api/v1/staff/dashboard'
import { Route as ApiV1StaffSessionRouteImport } from './routes/api/v1/staff/session'
import { Route as ApiV1AuthAdminLoginRouteImport } from './routes/api/v1/auth/admin/login'
import { Route as ApiV1AuthAssistantLoginRouteImport } from './routes/api/v1/auth/assistant/login'
import { Route as ApiV1AuthClientLoginRouteImport } from './routes/api/v1/auth/client/login'
import { Route as ApiV1StaffAssistantIndexRouteImport } from './routes/api/v1/staff/assistant/index'
import { Route as ApiV1StaffClientsIndexRouteImport } from './routes/api/v1/staff/clients/index'
import { Route as ApiV1StaffClientsIdRouteImport } from './routes/api/v1/staff/clients/$id'
import { Route as ApiV1StaffCredentialsIndexRouteImport } from './routes/api/v1/staff/credentials/index'
import { Route as ApiV1StaffExportIndexRouteImport } from './routes/api/v1/staff/export/index'
import { Route as ApiV1StaffFeedbackIndexRouteImport } from './routes/api/v1/staff/feedback/index'
import { Route as ApiV1StaffMaliIndexRouteImport } from './routes/api/v1/staff/mali/index'
import { Route as ApiV1StaffMaliDebtRouteImport } from './routes/api/v1/staff/mali/debt'
import { Route as ApiV1StaffMaliPaymentRouteImport } from './routes/api/v1/staff/mali/payment'
import { Route as ApiV1StaffNotificationsIndexRouteImport } from './routes/api/v1/staff/notifications/index'
import { Route as ApiV1StaffNotificationsReadRouteImport } from './routes/api/v1/staff/notifications/read'
import { Route as ApiV1StaffPackagesIndexRouteImport } from './routes/api/v1/staff/packages/index'
import { Route as ApiV1StaffPasswordIndexRouteImport } from './routes/api/v1/staff/password/index'
import { Route as ApiV1StaffTelegramIndexRouteImport } from './routes/api/v1/staff/telegram/index'
import { Route as ApiV1StaffTrackingIndexRouteImport } from './routes/api/v1/staff/tracking/index'
import { Route as ApiV1ClientDietsIdPdfRouteImport } from './routes/api/v1/client/diets.$id.pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CikisRoute = CikisRouteImport.update({
  id: '/cikis',
  path: '/cikis',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimdaRoute = HakkimdaRouteImport.update({
  id: '/hakkimda',
  path: '/hakkimda',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerRoute = HizmetlerRouteImport.update({
  id: '/hizmetler',
  path: '/hizmetler',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const RandevuRoute = RandevuRouteImport.update({
  id: '/randevu',
  path: '/randevu',
  getParentRoute: () => rootRouteImport,
} as any)
const SifremiUnuttumRoute = SifremiUnuttumRouteImport.update({
  id: '/sifremi-unuttum',
  path: '/sifremi-unuttum',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAsistanRoute = AdminAsistanRouteImport.update({
  id: '/asistan',
  path: '/asistan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBildirimlerRoute = AdminBildirimlerRouteImport.update({
  id: '/bildirimler',
  path: '/bildirimler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDanisanlarRoute = AdminDanisanlarRouteImport.update({
  id: '/danisanlar',
  path: '/danisanlar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGoruslerRoute = AdminGoruslerRouteImport.update({
  id: '/gorusler',
  path: '/gorusler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaliRoute = AdminMaliRouteImport.update({
  id: '/mali',
  path: '/mali',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaketlerRoute = AdminPaketlerRouteImport.update({
  id: '/paketler',
  path: '/paketler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRandevularRoute = AdminRandevularRouteImport.update({
  id: '/randevular',
  path: '/randevular',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSifrelerRoute = AdminSifrelerRouteImport.update({
  id: '/sifreler',
  path: '/sifreler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTahlillerRoute = AdminTahlillerRouteImport.update({
  id: '/tahliller',
  path: '/tahliller',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTelegramRoute = AdminTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AdminRoute,
} as any)
const AsistanGirisRoute = AsistanGirisRouteImport.update({
  id: '/asistan/giris',
  path: '/asistan/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelMesajRoute = PanelMesajRouteImport.update({
  id: '/mesaj',
  path: '/mesaj',
  getParentRoute: () => PanelRoute,
} as any)
const PanelProfilRoute = PanelProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSifreRoute = PanelSifreRouteImport.update({
  id: '/sifre',
  path: '/sifre',
  getParentRoute: () => PanelRoute,
} as any)
const RandevuIndexRoute = RandevuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RandevuRoute,
} as any)
const RandevuBasariliRoute = RandevuBasariliRouteImport.update({
  id: '/basarili',
  path: '/basarili',
  getParentRoute: () => RandevuRoute,
} as any)
const AdminDanisanIdRoute = AdminDanisanIdRouteImport.update({
  id: '/danisan/$id',
  path: '/danisan/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDanisanEkleRoute = AdminDanisanEkleRouteImport.update({
  id: '/danisan/ekle',
  path: '/danisan/ekle',
  getParentRoute: () => AdminRoute,
} as any)
const ApiV1AuthLogoutRoute = ApiV1AuthLogoutRouteImport.update({
  id: '/api/v1/auth/logout',
  path: '/api/v1/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthMeRoute = ApiV1AuthMeRouteImport.update({
  id: '/api/v1/auth/me',
  path: '/api/v1/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ClientDailyRoute = ApiV1ClientDailyRouteImport.update({
  id: '/api/v1/client/daily',
  path: '/api/v1/client/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ClientFastingRoute = ApiV1ClientFastingRouteImport.update({
  id: '/api/v1/client/fasting',
  path: '/api/v1/client/fasting',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ClientLabsRoute = ApiV1ClientLabsRouteImport.update({
  id: '/api/v1/client/labs',
  path: '/api/v1/client/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ClientMessagesRoute = ApiV1ClientMessagesRouteImport.update({
  id: '/api/v1/client/messages',
  path: '/api/v1/client/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ClientMindfulRoute = ApiV1ClientMindfulRouteImport.update({
  id: '/api/v1/client/mindful',
  path: '/api/v1/client/mindful',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ClientOffplanRoute = ApiV1ClientOffplanRouteImport.update({
  id: '/api/v1/client/offplan',
  path: '/api/v1/client/offplan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ClientPanelRoute = ApiV1ClientPanelRouteImport.update({
  id: '/api/v1/client/panel',
  path: '/api/v1/client/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ClientPasswordRoute = ApiV1ClientPasswordRouteImport.update({
  id: '/api/v1/client/password',
  path: '/api/v1/client/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ClientProfileRoute = ApiV1ClientProfileRouteImport.update({
  id: '/api/v1/client/profile',
  path: '/api/v1/client/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ClientWaterRoute = ApiV1ClientWaterRouteImport.update({
  id: '/api/v1/client/water',
  path: '/api/v1/client/water',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffAppointmentsRoute = ApiV1StaffAppointmentsRouteImport.update({
  id: '/api/v1/staff/appointments',
  path: '/api/v1/staff/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffDashboardRoute = ApiV1StaffDashboardRouteImport.update({
  id: '/api/v1/staff/dashboard',
  path: '/api/v1/staff/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffSessionRoute = ApiV1StaffSessionRouteImport.update({
  id: '/api/v1/staff/session',
  path: '/api/v1/staff/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthAdminLoginRoute = ApiV1AuthAdminLoginRouteImport.update({
  id: '/api/v1/auth/admin/login',
  path: '/api/v1/auth/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthAssistantLoginRoute = ApiV1AuthAssistantLoginRouteImport.update({
  id: '/api/v1/auth/assistant/login',
  path: '/api/v1/auth/assistant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthClientLoginRoute = ApiV1AuthClientLoginRouteImport.update({
  id: '/api/v1/auth/client/login',
  path: '/api/v1/auth/client/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffAssistantIndexRoute =
  ApiV1StaffAssistantIndexRouteImport.update({
    id: '/api/v1/staff/assistant/',
    path: '/api/v1/staff/assistant/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1StaffClientsIndexRoute = ApiV1StaffClientsIndexRouteImport.update({
  id: '/api/v1/staff/clients/',
  path: '/api/v1/staff/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffClientsIdRoute = ApiV1StaffClientsIdRouteImport.update({
  id: '/api/v1/staff/clients/$id',
  path: '/api/v1/staff/clients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffCredentialsIndexRoute =
  ApiV1StaffCredentialsIndexRouteImport.update({
    id: '/api/v1/staff/credentials/',
    path: '/api/v1/staff/credentials/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1StaffExportIndexRoute = ApiV1StaffExportIndexRouteImport.update({
  id: '/api/v1/staff/export/',
  path: '/api/v1/staff/export/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffFeedbackIndexRoute = ApiV1StaffFeedbackIndexRouteImport.update({
  id: '/api/v1/staff/feedback/',
  path: '/api/v1/staff/feedback/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffMaliIndexRoute = ApiV1StaffMaliIndexRouteImport.update({
  id: '/api/v1/staff/mali/',
  path: '/api/v1/staff/mali/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffMaliDebtRoute = ApiV1StaffMaliDebtRouteImport.update({
  id: '/api/v1/staff/mali/debt',
  path: '/api/v1/staff/mali/debt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffMaliPaymentRoute = ApiV1StaffMaliPaymentRouteImport.update({
  id: '/api/v1/staff/mali/payment',
  path: '/api/v1/staff/mali/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffNotificationsIndexRoute =
  ApiV1StaffNotificationsIndexRouteImport.update({
    id: '/api/v1/staff/notifications/',
    path: '/api/v1/staff/notifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1StaffNotificationsReadRoute =
  ApiV1StaffNotificationsReadRouteImport.update({
    id: '/api/v1/staff/notifications/read',
    path: '/api/v1/staff/notifications/read',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1StaffPackagesIndexRoute = ApiV1StaffPackagesIndexRouteImport.update({
  id: '/api/v1/staff/packages/',
  path: '/api/v1/staff/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffPasswordIndexRoute = ApiV1StaffPasswordIndexRouteImport.update({
  id: '/api/v1/staff/password/',
  path: '/api/v1/staff/password/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffTelegramIndexRoute = ApiV1StaffTelegramIndexRouteImport.update({
  id: '/api/v1/staff/telegram/',
  path: '/api/v1/staff/telegram/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffTrackingIndexRoute = ApiV1StaffTrackingIndexRouteImport.update({
  id: '/api/v1/staff/tracking/',
  path: '/api/v1/staff/tracking/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ClientDietsIdPdfRoute = ApiV1ClientDietsIdPdfRouteImport.update({
  id: '/api/v1/client/diets/$id/pdf',
  path: '/api/v1/client/diets/$id/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cikis': typeof CikisRoute
  '/cron': typeof CronRoute
  '/giris': typeof GirisRoute
  '/hakkimda': typeof HakkimdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/kvkk': typeof KvkkRoute
  '/panel': typeof PanelRouteWithChildren
  '/randevu': typeof RandevuRouteWithChildren
  '/sifremi-unuttum': typeof SifremiUnuttumRoute
  '/admin/asistan': typeof AdminAsistanRoute
  '/admin/bildirimler': typeof AdminBildirimlerRoute
  '/admin/danisanlar': typeof AdminDanisanlarRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/gorusler': typeof AdminGoruslerRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mali': typeof AdminMaliRoute
  '/admin/paketler': typeof AdminPaketlerRoute
  '/admin/randevular': typeof AdminRandevularRoute
  '/admin/sifreler': typeof AdminSifrelerRoute
  '/admin/tahliller': typeof AdminTahlillerRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/asistan/giris': typeof AsistanGirisRoute
  '/panel/mesaj': typeof PanelMesajRoute
  '/panel/profil': typeof PanelProfilRoute
  '/panel/sifre': typeof PanelSifreRoute
  '/randevu/basarili': typeof RandevuBasariliRoute
  '/admin/': typeof AdminIndexRoute
  '/panel/': typeof PanelIndexRoute
  '/randevu/': typeof RandevuIndexRoute
  '/admin/danisan/$id': typeof AdminDanisanIdRoute
  '/admin/danisan/ekle': typeof AdminDanisanEkleRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/client/daily': typeof ApiV1ClientDailyRoute
  '/api/v1/client/fasting': typeof ApiV1ClientFastingRoute
  '/api/v1/client/labs': typeof ApiV1ClientLabsRoute
  '/api/v1/client/messages': typeof ApiV1ClientMessagesRoute
  '/api/v1/client/mindful': typeof ApiV1ClientMindfulRoute
  '/api/v1/client/offplan': typeof ApiV1ClientOffplanRoute
  '/api/v1/client/panel': typeof ApiV1ClientPanelRoute
  '/api/v1/client/password': typeof ApiV1ClientPasswordRoute
  '/api/v1/client/profile': typeof ApiV1ClientProfileRoute
  '/api/v1/client/water': typeof ApiV1ClientWaterRoute
  '/api/v1/staff/appointments': typeof ApiV1StaffAppointmentsRoute
  '/api/v1/staff/dashboard': typeof ApiV1StaffDashboardRoute
  '/api/v1/staff/session': typeof ApiV1StaffSessionRoute
  '/api/v1/auth/admin/login': typeof ApiV1AuthAdminLoginRoute
  '/api/v1/auth/assistant/login': typeof ApiV1AuthAssistantLoginRoute
  '/api/v1/auth/client/login': typeof ApiV1AuthClientLoginRoute
  '/api/v1/staff/clients/$id': typeof ApiV1StaffClientsIdRoute
  '/api/v1/staff/mali/debt': typeof ApiV1StaffMaliDebtRoute
  '/api/v1/staff/mali/payment': typeof ApiV1StaffMaliPaymentRoute
  '/api/v1/staff/notifications/read': typeof ApiV1StaffNotificationsReadRoute
  '/api/v1/staff/assistant/': typeof ApiV1StaffAssistantIndexRoute
  '/api/v1/staff/clients/': typeof ApiV1StaffClientsIndexRoute
  '/api/v1/staff/credentials/': typeof ApiV1StaffCredentialsIndexRoute
  '/api/v1/staff/export/': typeof ApiV1StaffExportIndexRoute
  '/api/v1/staff/feedback/': typeof ApiV1StaffFeedbackIndexRoute
  '/api/v1/staff/mali/': typeof ApiV1StaffMaliIndexRoute
  '/api/v1/staff/notifications/': typeof ApiV1StaffNotificationsIndexRoute
  '/api/v1/staff/packages/': typeof ApiV1StaffPackagesIndexRoute
  '/api/v1/staff/password/': typeof ApiV1StaffPasswordIndexRoute
  '/api/v1/staff/telegram/': typeof ApiV1StaffTelegramIndexRoute
  '/api/v1/staff/tracking/': typeof ApiV1StaffTrackingIndexRoute
  '/api/v1/client/diets/$id/pdf': typeof ApiV1ClientDietsIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cikis': typeof CikisRoute
  '/cron': typeof CronRoute
  '/giris': typeof GirisRoute
  '/hakkimda': typeof HakkimdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/kvkk': typeof KvkkRoute
  '/sifremi-unuttum': typeof SifremiUnuttumRoute
  '/admin/asistan': typeof AdminAsistanRoute
  '/admin/bildirimler': typeof AdminBildirimlerRoute
  '/admin/danisanlar': typeof AdminDanisanlarRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/gorusler': typeof AdminGoruslerRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mali': typeof AdminMaliRoute
  '/admin/paketler': typeof AdminPaketlerRoute
  '/admin/randevular': typeof AdminRandevularRoute
  '/admin/sifreler': typeof AdminSifrelerRoute
  '/admin/tahliller': typeof AdminTahlillerRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/asistan/giris': typeof AsistanGirisRoute
  '/panel/mesaj': typeof PanelMesajRoute
  '/panel/profil': typeof PanelProfilRoute
  '/panel/sifre': typeof PanelSifreRoute
  '/randevu/basarili': typeof RandevuBasariliRoute
  '/admin': typeof AdminIndexRoute
  '/panel': typeof PanelIndexRoute
  '/randevu': typeof RandevuIndexRoute
  '/admin/danisan/$id': typeof AdminDanisanIdRoute
  '/admin/danisan/ekle': typeof AdminDanisanEkleRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/client/daily': typeof ApiV1ClientDailyRoute
  '/api/v1/client/fasting': typeof ApiV1ClientFastingRoute
  '/api/v1/client/labs': typeof ApiV1ClientLabsRoute
  '/api/v1/client/messages': typeof ApiV1ClientMessagesRoute
  '/api/v1/client/mindful': typeof ApiV1ClientMindfulRoute
  '/api/v1/client/offplan': typeof ApiV1ClientOffplanRoute
  '/api/v1/client/panel': typeof ApiV1ClientPanelRoute
  '/api/v1/client/password': typeof ApiV1ClientPasswordRoute
  '/api/v1/client/profile': typeof ApiV1ClientProfileRoute
  '/api/v1/client/water': typeof ApiV1ClientWaterRoute
  '/api/v1/staff/appointments': typeof ApiV1StaffAppointmentsRoute
  '/api/v1/staff/dashboard': typeof ApiV1StaffDashboardRoute
  '/api/v1/staff/session': typeof ApiV1StaffSessionRoute
  '/api/v1/auth/admin/login': typeof ApiV1AuthAdminLoginRoute
  '/api/v1/auth/assistant/login': typeof ApiV1AuthAssistantLoginRoute
  '/api/v1/auth/client/login': typeof ApiV1AuthClientLoginRoute
  '/api/v1/staff/clients/$id': typeof ApiV1StaffClientsIdRoute
  '/api/v1/staff/mali/debt': typeof ApiV1StaffMaliDebtRoute
  '/api/v1/staff/mali/payment': typeof ApiV1StaffMaliPaymentRoute
  '/api/v1/staff/notifications/read': typeof ApiV1StaffNotificationsReadRoute
  '/api/v1/staff/assistant': typeof ApiV1StaffAssistantIndexRoute
  '/api/v1/staff/clients': typeof ApiV1StaffClientsIndexRoute
  '/api/v1/staff/credentials': typeof ApiV1StaffCredentialsIndexRoute
  '/api/v1/staff/export': typeof ApiV1StaffExportIndexRoute
  '/api/v1/staff/feedback': typeof ApiV1StaffFeedbackIndexRoute
  '/api/v1/staff/mali': typeof ApiV1StaffMaliIndexRoute
  '/api/v1/staff/notifications': typeof ApiV1StaffNotificationsIndexRoute
  '/api/v1/staff/packages': typeof ApiV1StaffPackagesIndexRoute
  '/api/v1/staff/password': typeof ApiV1StaffPasswordIndexRoute
  '/api/v1/staff/telegram': typeof ApiV1StaffTelegramIndexRoute
  '/api/v1/staff/tracking': typeof ApiV1StaffTrackingIndexRoute
  '/api/v1/client/diets/$id/pdf': typeof ApiV1ClientDietsIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cikis': typeof CikisRoute
  '/cron': typeof CronRoute
  '/giris': typeof GirisRoute
  '/hakkimda': typeof HakkimdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/kvkk': typeof KvkkRoute
  '/panel': typeof PanelRouteWithChildren
  '/randevu': typeof RandevuRouteWithChildren
  '/sifremi-unuttum': typeof SifremiUnuttumRoute
  '/admin/asistan': typeof AdminAsistanRoute
  '/admin/bildirimler': typeof AdminBildirimlerRoute
  '/admin/danisanlar': typeof AdminDanisanlarRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/gorusler': typeof AdminGoruslerRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mali': typeof AdminMaliRoute
  '/admin/paketler': typeof AdminPaketlerRoute
  '/admin/randevular': typeof AdminRandevularRoute
  '/admin/sifreler': typeof AdminSifrelerRoute
  '/admin/tahliller': typeof AdminTahlillerRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/asistan/giris': typeof AsistanGirisRoute
  '/panel/mesaj': typeof PanelMesajRoute
  '/panel/profil': typeof PanelProfilRoute
  '/panel/sifre': typeof PanelSifreRoute
  '/randevu/basarili': typeof RandevuBasariliRoute
  '/admin/': typeof AdminIndexRoute
  '/panel/': typeof PanelIndexRoute
  '/randevu/': typeof RandevuIndexRoute
  '/admin/danisan/$id': typeof AdminDanisanIdRoute
  '/admin/danisan/ekle': typeof AdminDanisanEkleRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/client/daily': typeof ApiV1ClientDailyRoute
  '/api/v1/client/fasting': typeof ApiV1ClientFastingRoute
  '/api/v1/client/labs': typeof ApiV1ClientLabsRoute
  '/api/v1/client/messages': typeof ApiV1ClientMessagesRoute
  '/api/v1/client/mindful': typeof ApiV1ClientMindfulRoute
  '/api/v1/client/offplan': typeof ApiV1ClientOffplanRoute
  '/api/v1/client/panel': typeof ApiV1ClientPanelRoute
  '/api/v1/client/password': typeof ApiV1ClientPasswordRoute
  '/api/v1/client/profile': typeof ApiV1ClientProfileRoute
  '/api/v1/client/water': typeof ApiV1ClientWaterRoute
  '/api/v1/staff/appointments': typeof ApiV1StaffAppointmentsRoute
  '/api/v1/staff/dashboard': typeof ApiV1StaffDashboardRoute
  '/api/v1/staff/session': typeof ApiV1StaffSessionRoute
  '/api/v1/auth/admin/login': typeof ApiV1AuthAdminLoginRoute
  '/api/v1/auth/assistant/login': typeof ApiV1AuthAssistantLoginRoute
  '/api/v1/auth/client/login': typeof ApiV1AuthClientLoginRoute
  '/api/v1/staff/clients/$id': typeof ApiV1StaffClientsIdRoute
  '/api/v1/staff/mali/debt': typeof ApiV1StaffMaliDebtRoute
  '/api/v1/staff/mali/payment': typeof ApiV1StaffMaliPaymentRoute
  '/api/v1/staff/notifications/read': typeof ApiV1StaffNotificationsReadRoute
  '/api/v1/staff/assistant/': typeof ApiV1StaffAssistantIndexRoute
  '/api/v1/staff/clients/': typeof ApiV1StaffClientsIndexRoute
  '/api/v1/staff/credentials/': typeof ApiV1StaffCredentialsIndexRoute
  '/api/v1/staff/export/': typeof ApiV1StaffExportIndexRoute
  '/api/v1/staff/feedback/': typeof ApiV1StaffFeedbackIndexRoute
  '/api/v1/staff/mali/': typeof ApiV1StaffMaliIndexRoute
  '/api/v1/staff/notifications/': typeof ApiV1StaffNotificationsIndexRoute
  '/api/v1/staff/packages/': typeof ApiV1StaffPackagesIndexRoute
  '/api/v1/staff/password/': typeof ApiV1StaffPasswordIndexRoute
  '/api/v1/staff/telegram/': typeof ApiV1StaffTelegramIndexRoute
  '/api/v1/staff/tracking/': typeof ApiV1StaffTrackingIndexRoute
  '/api/v1/client/diets/$id/pdf': typeof ApiV1ClientDietsIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cikis'
    | '/cron'
    | '/giris'
    | '/hakkimda'
    | '/hizmetler'
    | '/iletisim'
    | '/kvkk'
    | '/panel'
    | '/randevu'
    | '/sifremi-unuttum'
    | '/admin/asistan'
    | '/admin/bildirimler'
    | '/admin/danisanlar'
    | '/admin/export'
    | '/admin/gorusler'
    | '/admin/login'
    | '/admin/mali'
    | '/admin/paketler'
    | '/admin/randevular'
    | '/admin/sifreler'
    | '/admin/tahliller'
    | '/admin/telegram'
    | '/asistan/giris'
    | '/panel/mesaj'
    | '/panel/profil'
    | '/panel/sifre'
    | '/randevu/basarili'
    | '/admin/'
    | '/panel/'
    | '/randevu/'
    | '/admin/danisan/$id'
    | '/admin/danisan/ekle'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/client/daily'
    | '/api/v1/client/fasting'
    | '/api/v1/client/labs'
    | '/api/v1/client/messages'
    | '/api/v1/client/mindful'
    | '/api/v1/client/offplan'
    | '/api/v1/client/panel'
    | '/api/v1/client/password'
    | '/api/v1/client/profile'
    | '/api/v1/client/water'
    | '/api/v1/staff/appointments'
    | '/api/v1/staff/dashboard'
    | '/api/v1/staff/session'
    | '/api/v1/auth/admin/login'
    | '/api/v1/auth/assistant/login'
    | '/api/v1/auth/client/login'
    | '/api/v1/staff/clients/$id'
    | '/api/v1/staff/mali/debt'
    | '/api/v1/staff/mali/payment'
    | '/api/v1/staff/notifications/read'
    | '/api/v1/staff/assistant/'
    | '/api/v1/staff/clients/'
    | '/api/v1/staff/credentials/'
    | '/api/v1/staff/export/'
    | '/api/v1/staff/feedback/'
    | '/api/v1/staff/mali/'
    | '/api/v1/staff/notifications/'
    | '/api/v1/staff/packages/'
    | '/api/v1/staff/password/'
    | '/api/v1/staff/telegram/'
    | '/api/v1/staff/tracking/'
    | '/api/v1/client/diets/$id/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cikis'
    | '/cron'
    | '/giris'
    | '/hakkimda'
    | '/hizmetler'
    | '/iletisim'
    | '/kvkk'
    | '/sifremi-unuttum'
    | '/admin/asistan'
    | '/admin/bildirimler'
    | '/admin/danisanlar'
    | '/admin/export'
    | '/admin/gorusler'
    | '/admin/login'
    | '/admin/mali'
    | '/admin/paketler'
    | '/admin/randevular'
    | '/admin/sifreler'
    | '/admin/tahliller'
    | '/admin/telegram'
    | '/asistan/giris'
    | '/panel/mesaj'
    | '/panel/profil'
    | '/panel/sifre'
    | '/randevu/basarili'
    | '/admin'
    | '/panel'
    | '/randevu'
    | '/admin/danisan/$id'
    | '/admin/danisan/ekle'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/client/daily'
    | '/api/v1/client/fasting'
    | '/api/v1/client/labs'
    | '/api/v1/client/messages'
    | '/api/v1/client/mindful'
    | '/api/v1/client/offplan'
    | '/api/v1/client/panel'
    | '/api/v1/client/password'
    | '/api/v1/client/profile'
    | '/api/v1/client/water'
    | '/api/v1/staff/appointments'
    | '/api/v1/staff/dashboard'
    | '/api/v1/staff/session'
    | '/api/v1/auth/admin/login'
    | '/api/v1/auth/assistant/login'
    | '/api/v1/auth/client/login'
    | '/api/v1/staff/clients/$id'
    | '/api/v1/staff/mali/debt'
    | '/api/v1/staff/mali/payment'
    | '/api/v1/staff/notifications/read'
    | '/api/v1/staff/assistant'
    | '/api/v1/staff/clients'
    | '/api/v1/staff/credentials'
    | '/api/v1/staff/export'
    | '/api/v1/staff/feedback'
    | '/api/v1/staff/mali'
    | '/api/v1/staff/notifications'
    | '/api/v1/staff/packages'
    | '/api/v1/staff/password'
    | '/api/v1/staff/telegram'
    | '/api/v1/staff/tracking'
    | '/api/v1/client/diets/$id/pdf'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cikis'
    | '/cron'
    | '/giris'
    | '/hakkimda'
    | '/hizmetler'
    | '/iletisim'
    | '/kvkk'
    | '/panel'
    | '/randevu'
    | '/sifremi-unuttum'
    | '/admin/asistan'
    | '/admin/bildirimler'
    | '/admin/danisanlar'
    | '/admin/export'
    | '/admin/gorusler'
    | '/admin/login'
    | '/admin/mali'
    | '/admin/paketler'
    | '/admin/randevular'
    | '/admin/sifreler'
    | '/admin/tahliller'
    | '/admin/telegram'
    | '/asistan/giris'
    | '/panel/mesaj'
    | '/panel/profil'
    | '/panel/sifre'
    | '/randevu/basarili'
    | '/admin/'
    | '/panel/'
    | '/randevu/'
    | '/admin/danisan/$id'
    | '/admin/danisan/ekle'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/client/daily'
    | '/api/v1/client/fasting'
    | '/api/v1/client/labs'
    | '/api/v1/client/messages'
    | '/api/v1/client/mindful'
    | '/api/v1/client/offplan'
    | '/api/v1/client/panel'
    | '/api/v1/client/password'
    | '/api/v1/client/profile'
    | '/api/v1/client/water'
    | '/api/v1/staff/appointments'
    | '/api/v1/staff/dashboard'
    | '/api/v1/staff/session'
    | '/api/v1/auth/admin/login'
    | '/api/v1/auth/assistant/login'
    | '/api/v1/auth/client/login'
    | '/api/v1/staff/clients/$id'
    | '/api/v1/staff/mali/debt'
    | '/api/v1/staff/mali/payment'
    | '/api/v1/staff/notifications/read'
    | '/api/v1/staff/assistant/'
    | '/api/v1/staff/clients/'
    | '/api/v1/staff/credentials/'
    | '/api/v1/staff/export/'
    | '/api/v1/staff/feedback/'
    | '/api/v1/staff/mali/'
    | '/api/v1/staff/notifications/'
    | '/api/v1/staff/packages/'
    | '/api/v1/staff/password/'
    | '/api/v1/staff/telegram/'
    | '/api/v1/staff/tracking/'
    | '/api/v1/client/diets/$id/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CikisRoute: typeof CikisRoute
  CronRoute: typeof CronRoute
  GirisRoute: typeof GirisRoute
  HakkimdaRoute: typeof HakkimdaRoute
  HizmetlerRoute: typeof HizmetlerRoute
  IletisimRoute: typeof IletisimRoute
  KvkkRoute: typeof KvkkRoute
  PanelRoute: typeof PanelRouteWithChildren
  RandevuRoute: typeof RandevuRouteWithChildren
  SifremiUnuttumRoute: typeof SifremiUnuttumRoute
  AsistanGirisRoute: typeof AsistanGirisRoute
  ApiV1AuthLogoutRoute: typeof ApiV1AuthLogoutRoute
  ApiV1AuthMeRoute: typeof ApiV1AuthMeRoute
  ApiV1ClientDailyRoute: typeof ApiV1ClientDailyRoute
  ApiV1ClientFastingRoute: typeof ApiV1ClientFastingRoute
  ApiV1ClientLabsRoute: typeof ApiV1ClientLabsRoute
  ApiV1ClientMessagesRoute: typeof ApiV1ClientMessagesRoute
  ApiV1ClientMindfulRoute: typeof ApiV1ClientMindfulRoute
  ApiV1ClientOffplanRoute: typeof ApiV1ClientOffplanRoute
  ApiV1ClientPanelRoute: typeof ApiV1ClientPanelRoute
  ApiV1ClientPasswordRoute: typeof ApiV1ClientPasswordRoute
  ApiV1ClientProfileRoute: typeof ApiV1ClientProfileRoute
  ApiV1ClientWaterRoute: typeof ApiV1ClientWaterRoute
  ApiV1StaffAppointmentsRoute: typeof ApiV1StaffAppointmentsRoute
  ApiV1StaffDashboardRoute: typeof ApiV1StaffDashboardRoute
  ApiV1StaffSessionRoute: typeof ApiV1StaffSessionRoute
  ApiV1AuthAdminLoginRoute: typeof ApiV1AuthAdminLoginRoute
  ApiV1AuthAssistantLoginRoute: typeof ApiV1AuthAssistantLoginRoute
  ApiV1AuthClientLoginRoute: typeof ApiV1AuthClientLoginRoute
  ApiV1StaffClientsIdRoute: typeof ApiV1StaffClientsIdRoute
  ApiV1StaffMaliDebtRoute: typeof ApiV1StaffMaliDebtRoute
  ApiV1StaffMaliPaymentRoute: typeof ApiV1StaffMaliPaymentRoute
  ApiV1StaffNotificationsReadRoute: typeof ApiV1StaffNotificationsReadRoute
  ApiV1StaffAssistantIndexRoute: typeof ApiV1StaffAssistantIndexRoute
  ApiV1StaffClientsIndexRoute: typeof ApiV1StaffClientsIndexRoute
  ApiV1StaffCredentialsIndexRoute: typeof ApiV1StaffCredentialsIndexRoute
  ApiV1StaffExportIndexRoute: typeof ApiV1StaffExportIndexRoute
  ApiV1StaffFeedbackIndexRoute: typeof ApiV1StaffFeedbackIndexRoute
  ApiV1StaffMaliIndexRoute: typeof ApiV1StaffMaliIndexRoute
  ApiV1StaffNotificationsIndexRoute: typeof ApiV1StaffNotificationsIndexRoute
  ApiV1StaffPackagesIndexRoute: typeof ApiV1StaffPackagesIndexRoute
  ApiV1StaffPasswordIndexRoute: typeof ApiV1StaffPasswordIndexRoute
  ApiV1StaffTelegramIndexRoute: typeof ApiV1StaffTelegramIndexRoute
  ApiV1StaffTrackingIndexRoute: typeof ApiV1StaffTrackingIndexRoute
  ApiV1ClientDietsIdPdfRoute: typeof ApiV1ClientDietsIdPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cikis': {
      id: '/cikis'
      path: '/cikis'
      fullPath: '/cikis'
      preLoaderRoute: typeof CikisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimda': {
      id: '/hakkimda'
      path: '/hakkimda'
      fullPath: '/hakkimda'
      preLoaderRoute: typeof HakkimdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetler': {
      id: '/hizmetler'
      path: '/hizmetler'
      fullPath: '/hizmetler'
      preLoaderRoute: typeof HizmetlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/randevu': {
      id: '/randevu'
      path: '/randevu'
      fullPath: '/randevu'
      preLoaderRoute: typeof RandevuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sifremi-unuttum': {
      id: '/sifremi-unuttum'
      path: '/sifremi-unuttum'
      fullPath: '/sifremi-unuttum'
      preLoaderRoute: typeof SifremiUnuttumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/asistan': {
      id: '/admin/asistan'
      path: '/asistan'
      fullPath: '/admin/asistan'
      preLoaderRoute: typeof AdminAsistanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bildirimler': {
      id: '/admin/bildirimler'
      path: '/bildirimler'
      fullPath: '/admin/bildirimler'
      preLoaderRoute: typeof AdminBildirimlerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/danisanlar': {
      id: '/admin/danisanlar'
      path: '/danisanlar'
      fullPath: '/admin/danisanlar'
      preLoaderRoute: typeof AdminDanisanlarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gorusler': {
      id: '/admin/gorusler'
      path: '/gorusler'
      fullPath: '/admin/gorusler'
      preLoaderRoute: typeof AdminGoruslerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mali': {
      id: '/admin/mali'
      path: '/mali'
      fullPath: '/admin/mali'
      preLoaderRoute: typeof AdminMaliRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paketler': {
      id: '/admin/paketler'
      path: '/paketler'
      fullPath: '/admin/paketler'
      preLoaderRoute: typeof AdminPaketlerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/randevular': {
      id: '/admin/randevular'
      path: '/randevular'
      fullPath: '/admin/randevular'
      preLoaderRoute: typeof AdminRandevularRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sifreler': {
      id: '/admin/sifreler'
      path: '/sifreler'
      fullPath: '/admin/sifreler'
      preLoaderRoute: typeof AdminSifrelerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tahliller': {
      id: '/admin/tahliller'
      path: '/tahliller'
      fullPath: '/admin/tahliller'
      preLoaderRoute: typeof AdminTahlillerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/telegram': {
      id: '/admin/telegram'
      path: '/telegram'
      fullPath: '/admin/telegram'
      preLoaderRoute: typeof AdminTelegramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/asistan/giris': {
      id: '/asistan/giris'
      path: '/asistan/giris'
      fullPath: '/asistan/giris'
      preLoaderRoute: typeof AsistanGirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/mesaj': {
      id: '/panel/mesaj'
      path: '/mesaj'
      fullPath: '/panel/mesaj'
      preLoaderRoute: typeof PanelMesajRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/profil': {
      id: '/panel/profil'
      path: '/profil'
      fullPath: '/panel/profil'
      preLoaderRoute: typeof PanelProfilRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/sifre': {
      id: '/panel/sifre'
      path: '/sifre'
      fullPath: '/panel/sifre'
      preLoaderRoute: typeof PanelSifreRouteImport
      parentRoute: typeof PanelRoute
    }
    '/randevu/': {
      id: '/randevu/'
      path: '/'
      fullPath: '/randevu/'
      preLoaderRoute: typeof RandevuIndexRouteImport
      parentRoute: typeof RandevuRoute
    }
    '/randevu/basarili': {
      id: '/randevu/basarili'
      path: '/basarili'
      fullPath: '/randevu/basarili'
      preLoaderRoute: typeof RandevuBasariliRouteImport
      parentRoute: typeof RandevuRoute
    }
    '/admin/danisan/$id': {
      id: '/admin/danisan/$id'
      path: '/danisan/$id'
      fullPath: '/admin/danisan/$id'
      preLoaderRoute: typeof AdminDanisanIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/danisan/ekle': {
      id: '/admin/danisan/ekle'
      path: '/danisan/ekle'
      fullPath: '/admin/danisan/ekle'
      preLoaderRoute: typeof AdminDanisanEkleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/v1/auth/logout': {
      id: '/api/v1/auth/logout'
      path: '/api/v1/auth/logout'
      fullPath: '/api/v1/auth/logout'
      preLoaderRoute: typeof ApiV1AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/me': {
      id: '/api/v1/auth/me'
      path: '/api/v1/auth/me'
      fullPath: '/api/v1/auth/me'
      preLoaderRoute: typeof ApiV1AuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/client/daily': {
      id: '/api/v1/client/daily'
      path: '/api/v1/client/daily'
      fullPath: '/api/v1/client/daily'
      preLoaderRoute: typeof ApiV1ClientDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/client/fasting': {
      id: '/api/v1/client/fasting'
      path: '/api/v1/client/fasting'
      fullPath: '/api/v1/client/fasting'
      preLoaderRoute: typeof ApiV1ClientFastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/client/labs': {
      id: '/api/v1/client/labs'
      path: '/api/v1/client/labs'
      fullPath: '/api/v1/client/labs'
      preLoaderRoute: typeof ApiV1ClientLabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/client/messages': {
      id: '/api/v1/client/messages'
      path: '/api/v1/client/messages'
      fullPath: '/api/v1/client/messages'
      preLoaderRoute: typeof ApiV1ClientMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/client/mindful': {
      id: '/api/v1/client/mindful'
      path: '/api/v1/client/mindful'
      fullPath: '/api/v1/client/mindful'
      preLoaderRoute: typeof ApiV1ClientMindfulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/client/offplan': {
      id: '/api/v1/client/offplan'
      path: '/api/v1/client/offplan'
      fullPath: '/api/v1/client/offplan'
      preLoaderRoute: typeof ApiV1ClientOffplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/client/panel': {
      id: '/api/v1/client/panel'
      path: '/api/v1/client/panel'
      fullPath: '/api/v1/client/panel'
      preLoaderRoute: typeof ApiV1ClientPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/client/password': {
      id: '/api/v1/client/password'
      path: '/api/v1/client/password'
      fullPath: '/api/v1/client/password'
      preLoaderRoute: typeof ApiV1ClientPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/client/profile': {
      id: '/api/v1/client/profile'
      path: '/api/v1/client/profile'
      fullPath: '/api/v1/client/profile'
      preLoaderRoute: typeof ApiV1ClientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/client/water': {
      id: '/api/v1/client/water'
      path: '/api/v1/client/water'
      fullPath: '/api/v1/client/water'
      preLoaderRoute: typeof ApiV1ClientWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/appointments': {
      id: '/api/v1/staff/appointments'
      path: '/api/v1/staff/appointments'
      fullPath: '/api/v1/staff/appointments'
      preLoaderRoute: typeof ApiV1StaffAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/dashboard': {
      id: '/api/v1/staff/dashboard'
      path: '/api/v1/staff/dashboard'
      fullPath: '/api/v1/staff/dashboard'
      preLoaderRoute: typeof ApiV1StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/session': {
      id: '/api/v1/staff/session'
      path: '/api/v1/staff/session'
      fullPath: '/api/v1/staff/session'
      preLoaderRoute: typeof ApiV1StaffSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/admin/login': {
      id: '/api/v1/auth/admin/login'
      path: '/api/v1/auth/admin/login'
      fullPath: '/api/v1/auth/admin/login'
      preLoaderRoute: typeof ApiV1AuthAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/assistant/login': {
      id: '/api/v1/auth/assistant/login'
      path: '/api/v1/auth/assistant/login'
      fullPath: '/api/v1/auth/assistant/login'
      preLoaderRoute: typeof ApiV1AuthAssistantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/client/login': {
      id: '/api/v1/auth/client/login'
      path: '/api/v1/auth/client/login'
      fullPath: '/api/v1/auth/client/login'
      preLoaderRoute: typeof ApiV1AuthClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/assistant/': {
      id: '/api/v1/staff/assistant/'
      path: '/api/v1/staff/assistant'
      fullPath: '/api/v1/staff/assistant/'
      preLoaderRoute: typeof ApiV1StaffAssistantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/clients/': {
      id: '/api/v1/staff/clients/'
      path: '/api/v1/staff/clients'
      fullPath: '/api/v1/staff/clients/'
      preLoaderRoute: typeof ApiV1StaffClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/clients/$id': {
      id: '/api/v1/staff/clients/$id'
      path: '/api/v1/staff/clients/$id'
      fullPath: '/api/v1/staff/clients/$id'
      preLoaderRoute: typeof ApiV1StaffClientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/credentials/': {
      id: '/api/v1/staff/credentials/'
      path: '/api/v1/staff/credentials'
      fullPath: '/api/v1/staff/credentials/'
      preLoaderRoute: typeof ApiV1StaffCredentialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/export/': {
      id: '/api/v1/staff/export/'
      path: '/api/v1/staff/export'
      fullPath: '/api/v1/staff/export/'
      preLoaderRoute: typeof ApiV1StaffExportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/feedback/': {
      id: '/api/v1/staff/feedback/'
      path: '/api/v1/staff/feedback'
      fullPath: '/api/v1/staff/feedback/'
      preLoaderRoute: typeof ApiV1StaffFeedbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/mali/': {
      id: '/api/v1/staff/mali/'
      path: '/api/v1/staff/mali'
      fullPath: '/api/v1/staff/mali/'
      preLoaderRoute: typeof ApiV1StaffMaliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/mali/debt': {
      id: '/api/v1/staff/mali/debt'
      path: '/api/v1/staff/mali/debt'
      fullPath: '/api/v1/staff/mali/debt'
      preLoaderRoute: typeof ApiV1StaffMaliDebtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/mali/payment': {
      id: '/api/v1/staff/mali/payment'
      path: '/api/v1/staff/mali/payment'
      fullPath: '/api/v1/staff/mali/payment'
      preLoaderRoute: typeof ApiV1StaffMaliPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/notifications/': {
      id: '/api/v1/staff/notifications/'
      path: '/api/v1/staff/notifications'
      fullPath: '/api/v1/staff/notifications/'
      preLoaderRoute: typeof ApiV1StaffNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/notifications/read': {
      id: '/api/v1/staff/notifications/read'
      path: '/api/v1/staff/notifications/read'
      fullPath: '/api/v1/staff/notifications/read'
      preLoaderRoute: typeof ApiV1StaffNotificationsReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/packages/': {
      id: '/api/v1/staff/packages/'
      path: '/api/v1/staff/packages'
      fullPath: '/api/v1/staff/packages/'
      preLoaderRoute: typeof ApiV1StaffPackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/password/': {
      id: '/api/v1/staff/password/'
      path: '/api/v1/staff/password'
      fullPath: '/api/v1/staff/password/'
      preLoaderRoute: typeof ApiV1StaffPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/telegram/': {
      id: '/api/v1/staff/telegram/'
      path: '/api/v1/staff/telegram'
      fullPath: '/api/v1/staff/telegram/'
      preLoaderRoute: typeof ApiV1StaffTelegramIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/tracking/': {
      id: '/api/v1/staff/tracking/'
      path: '/api/v1/staff/tracking'
      fullPath: '/api/v1/staff/tracking/'
      preLoaderRoute: typeof ApiV1StaffTrackingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/client/diets/$id/pdf': {
      id: '/api/v1/client/diets/$id/pdf'
      path: '/api/v1/client/diets/$id/pdf'
      fullPath: '/api/v1/client/diets/$id/pdf'
      preLoaderRoute: typeof ApiV1ClientDietsIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAsistanRoute: typeof AdminAsistanRoute
  AdminBildirimlerRoute: typeof AdminBildirimlerRoute
  AdminDanisanlarRoute: typeof AdminDanisanlarRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminGoruslerRoute: typeof AdminGoruslerRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMaliRoute: typeof AdminMaliRoute
  AdminPaketlerRoute: typeof AdminPaketlerRoute
  AdminRandevularRoute: typeof AdminRandevularRoute
  AdminSifrelerRoute: typeof AdminSifrelerRoute
  AdminTahlillerRoute: typeof AdminTahlillerRoute
  AdminTelegramRoute: typeof AdminTelegramRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDanisanIdRoute: typeof AdminDanisanIdRoute
  AdminDanisanEkleRoute: typeof AdminDanisanEkleRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAsistanRoute: AdminAsistanRoute,
  AdminBildirimlerRoute: AdminBildirimlerRoute,
  AdminDanisanlarRoute: AdminDanisanlarRoute,
  AdminExportRoute: AdminExportRoute,
  AdminGoruslerRoute: AdminGoruslerRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMaliRoute: AdminMaliRoute,
  AdminPaketlerRoute: AdminPaketlerRoute,
  AdminRandevularRoute: AdminRandevularRoute,
  AdminSifrelerRoute: AdminSifrelerRoute,
  AdminTahlillerRoute: AdminTahlillerRoute,
  AdminTelegramRoute: AdminTelegramRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDanisanIdRoute: AdminDanisanIdRoute,
  AdminDanisanEkleRoute: AdminDanisanEkleRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PanelRouteChildren {
  PanelMesajRoute: typeof PanelMesajRoute
  PanelProfilRoute: typeof PanelProfilRoute
  PanelSifreRoute: typeof PanelSifreRoute
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelMesajRoute: PanelMesajRoute,
  PanelProfilRoute: PanelProfilRoute,
  PanelSifreRoute: PanelSifreRoute,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

interface RandevuRouteChildren {
  RandevuBasariliRoute: typeof RandevuBasariliRoute
  RandevuIndexRoute: typeof RandevuIndexRoute
}

const RandevuRouteChildren: RandevuRouteChildren = {
  RandevuBasariliRoute: RandevuBasariliRoute,
  RandevuIndexRoute: RandevuIndexRoute,
}

const RandevuRouteWithChildren =
  RandevuRoute._addFileChildren(RandevuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CikisRoute: CikisRoute,
  CronRoute: CronRoute,
  GirisRoute: GirisRoute,
  HakkimdaRoute: HakkimdaRoute,
  HizmetlerRoute: HizmetlerRoute,
  IletisimRoute: IletisimRoute,
  KvkkRoute: KvkkRoute,
  PanelRoute: PanelRouteWithChildren,
  RandevuRoute: RandevuRouteWithChildren,
  SifremiUnuttumRoute: SifremiUnuttumRoute,
  AsistanGirisRoute: AsistanGirisRoute,
  ApiV1AuthLogoutRoute: ApiV1AuthLogoutRoute,
  ApiV1AuthMeRoute: ApiV1AuthMeRoute,
  ApiV1ClientDailyRoute: ApiV1ClientDailyRoute,
  ApiV1ClientFastingRoute: ApiV1ClientFastingRoute,
  ApiV1ClientLabsRoute: ApiV1ClientLabsRoute,
  ApiV1ClientMessagesRoute: ApiV1ClientMessagesRoute,
  ApiV1ClientMindfulRoute: ApiV1ClientMindfulRoute,
  ApiV1ClientOffplanRoute: ApiV1ClientOffplanRoute,
  ApiV1ClientPanelRoute: ApiV1ClientPanelRoute,
  ApiV1ClientPasswordRoute: ApiV1ClientPasswordRoute,
  ApiV1ClientProfileRoute: ApiV1ClientProfileRoute,
  ApiV1ClientWaterRoute: ApiV1ClientWaterRoute,
  ApiV1StaffAppointmentsRoute: ApiV1StaffAppointmentsRoute,
  ApiV1StaffDashboardRoute: ApiV1StaffDashboardRoute,
  ApiV1StaffSessionRoute: ApiV1StaffSessionRoute,
  ApiV1AuthAdminLoginRoute: ApiV1AuthAdminLoginRoute,
  ApiV1AuthAssistantLoginRoute: ApiV1AuthAssistantLoginRoute,
  ApiV1AuthClientLoginRoute: ApiV1AuthClientLoginRoute,
  ApiV1StaffClientsIdRoute: ApiV1StaffClientsIdRoute,
  ApiV1StaffMaliDebtRoute: ApiV1StaffMaliDebtRoute,
  ApiV1StaffMaliPaymentRoute: ApiV1StaffMaliPaymentRoute,
  ApiV1StaffNotificationsReadRoute: ApiV1StaffNotificationsReadRoute,
  ApiV1StaffAssistantIndexRoute: ApiV1StaffAssistantIndexRoute,
  ApiV1StaffClientsIndexRoute: ApiV1StaffClientsIndexRoute,
  ApiV1StaffCredentialsIndexRoute: ApiV1StaffCredentialsIndexRoute,
  ApiV1StaffExportIndexRoute: ApiV1StaffExportIndexRoute,
  ApiV1StaffFeedbackIndexRoute: ApiV1StaffFeedbackIndexRoute,
  ApiV1StaffMaliIndexRoute: ApiV1StaffMaliIndexRoute,
  ApiV1StaffNotificationsIndexRoute: ApiV1StaffNotificationsIndexRoute,
  ApiV1StaffPackagesIndexRoute: ApiV1StaffPackagesIndexRoute,
  ApiV1StaffPasswordIndexRoute: ApiV1StaffPasswordIndexRoute,
  ApiV1StaffTelegramIndexRoute: ApiV1StaffTelegramIndexRoute,
  ApiV1StaffTrackingIndexRoute: ApiV1StaffTrackingIndexRoute,
  ApiV1ClientDietsIdPdfRoute: ApiV1ClientDietsIdPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
