/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CikisRouteImport } from './routes/cikis'
import { Route as CronRouteImport } from './routes/cron'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as HakkimdaRouteImport } from './routes/hakkimda'
import { Route as HizmetlerRouteImport } from './routes/hizmetler'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as RandevuRouteImport } from './routes/randevu'
import { Route as SifremiUnuttumRouteImport } from './routes/sifremi-unuttum'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAsistanRouteImport } from './routes/admin.asistan'
import { Route as AdminBildirimlerRouteImport } from './routes/admin.bildirimler'
import { Route as AdminDanisanlarRouteImport } from './routes/admin.danisanlar'
import { Route as AdminExportRouteImport } from './routes/admin.export'
import { Route as AdminGoruslerRouteImport } from './routes/admin.gorusler'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMaliRouteImport } from './routes/admin.mali'
import { Route as AdminPaketlerRouteImport } from './routes/admin.paketler'
import { Route as AdminRandevularRouteImport } from './routes/admin.randevular'
import { Route as AdminSifrelerRouteImport } from './routes/admin.sifreler'
import { Route as AdminTahlillerRouteImport } from './routes/admin.tahliller'
import { Route as AdminTelegramRouteImport } from './routes/admin.telegram'
import { Route as AsistanGirisRouteImport } from './routes/asistan.giris'
import { Route as PanelIndexRouteImport } from './routes/panel.index'
import { Route as PanelMesajRouteImport } from './routes/panel.mesaj'
import { Route as PanelProfilRouteImport } from './routes/panel.profil'
import { Route as PanelSifreRouteImport } from './routes/panel.sifre'
import { Route as RandevuIndexRouteImport } from './routes/randevu.index'
import { Route as RandevuBasariliRouteImport } from './routes/randevu.basarili'
import { Route as AdminDanisanIdRouteImport } from './routes/admin.danisan.$id'
import { Route as AdminDanisanEkleRouteImport } from './routes/admin.danisan.ekle'
import { Route as ApiV1AuthLogoutRouteImport } from './routes/api/v1/auth/logout'
import { Route as ApiV1AuthMeRouteImport } from './routes/api/v1/auth/me'
import { Route as ApiV1ClientPanelRouteImport } from './routes/api/v1/client/panel'
import { Route as ApiV1StaffSessionRouteImport } from './routes/api/v1/staff/session'
import { Route as ApiV1AuthAdminLoginRouteImport } from './routes/api/v1/auth/admin/login'
import { Route as ApiV1AuthAssistantLoginRouteImport } from './routes/api/v1/auth/assistant/login'
import { Route as ApiV1AuthClientLoginRouteImport } from './routes/api/v1/auth/client/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CikisRoute = CikisRouteImport.update({
  id: '/cikis',
  path: '/cikis',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimdaRoute = HakkimdaRouteImport.update({
  id: '/hakkimda',
  path: '/hakkimda',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerRoute = HizmetlerRouteImport.update({
  id: '/hizmetler',
  path: '/hizmetler',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const RandevuRoute = RandevuRouteImport.update({
  id: '/randevu',
  path: '/randevu',
  getParentRoute: () => rootRouteImport,
} as any)
const SifremiUnuttumRoute = SifremiUnuttumRouteImport.update({
  id: '/sifremi-unuttum',
  path: '/sifremi-unuttum',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAsistanRoute = AdminAsistanRouteImport.update({
  id: '/asistan',
  path: '/asistan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBildirimlerRoute = AdminBildirimlerRouteImport.update({
  id: '/bildirimler',
  path: '/bildirimler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDanisanlarRoute = AdminDanisanlarRouteImport.update({
  id: '/danisanlar',
  path: '/danisanlar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGoruslerRoute = AdminGoruslerRouteImport.update({
  id: '/gorusler',
  path: '/gorusler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaliRoute = AdminMaliRouteImport.update({
  id: '/mali',
  path: '/mali',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaketlerRoute = AdminPaketlerRouteImport.update({
  id: '/paketler',
  path: '/paketler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRandevularRoute = AdminRandevularRouteImport.update({
  id: '/randevular',
  path: '/randevular',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSifrelerRoute = AdminSifrelerRouteImport.update({
  id: '/sifreler',
  path: '/sifreler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTahlillerRoute = AdminTahlillerRouteImport.update({
  id: '/tahliller',
  path: '/tahliller',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTelegramRoute = AdminTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AdminRoute,
} as any)
const AsistanGirisRoute = AsistanGirisRouteImport.update({
  id: '/asistan/giris',
  path: '/asistan/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelMesajRoute = PanelMesajRouteImport.update({
  id: '/mesaj',
  path: '/mesaj',
  getParentRoute: () => PanelRoute,
} as any)
const PanelProfilRoute = PanelProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSifreRoute = PanelSifreRouteImport.update({
  id: '/sifre',
  path: '/sifre',
  getParentRoute: () => PanelRoute,
} as any)
const RandevuIndexRoute = RandevuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RandevuRoute,
} as any)
const RandevuBasariliRoute = RandevuBasariliRouteImport.update({
  id: '/basarili',
  path: '/basarili',
  getParentRoute: () => RandevuRoute,
} as any)
const AdminDanisanIdRoute = AdminDanisanIdRouteImport.update({
  id: '/danisan/$id',
  path: '/danisan/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDanisanEkleRoute = AdminDanisanEkleRouteImport.update({
  id: '/danisan/ekle',
  path: '/danisan/ekle',
  getParentRoute: () => AdminRoute,
} as any)
const ApiV1AuthLogoutRoute = ApiV1AuthLogoutRouteImport.update({
  id: '/api/v1/auth/logout',
  path: '/api/v1/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthMeRoute = ApiV1AuthMeRouteImport.update({
  id: '/api/v1/auth/me',
  path: '/api/v1/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ClientPanelRoute = ApiV1ClientPanelRouteImport.update({
  id: '/api/v1/client/panel',
  path: '/api/v1/client/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffSessionRoute = ApiV1StaffSessionRouteImport.update({
  id: '/api/v1/staff/session',
  path: '/api/v1/staff/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthAdminLoginRoute = ApiV1AuthAdminLoginRouteImport.update({
  id: '/api/v1/auth/admin/login',
  path: '/api/v1/auth/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthAssistantLoginRoute = ApiV1AuthAssistantLoginRouteImport.update({
  id: '/api/v1/auth/assistant/login',
  path: '/api/v1/auth/assistant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthClientLoginRoute = ApiV1AuthClientLoginRouteImport.update({
  id: '/api/v1/auth/client/login',
  path: '/api/v1/auth/client/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cikis': typeof CikisRoute
  '/cron': typeof CronRoute
  '/giris': typeof GirisRoute
  '/hakkimda': typeof HakkimdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/kvkk': typeof KvkkRoute
  '/panel': typeof PanelRouteWithChildren
  '/randevu': typeof RandevuRouteWithChildren
  '/sifremi-unuttum': typeof SifremiUnuttumRoute
  '/admin/asistan': typeof AdminAsistanRoute
  '/admin/bildirimler': typeof AdminBildirimlerRoute
  '/admin/danisanlar': typeof AdminDanisanlarRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/gorusler': typeof AdminGoruslerRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mali': typeof AdminMaliRoute
  '/admin/paketler': typeof AdminPaketlerRoute
  '/admin/randevular': typeof AdminRandevularRoute
  '/admin/sifreler': typeof AdminSifrelerRoute
  '/admin/tahliller': typeof AdminTahlillerRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/asistan/giris': typeof AsistanGirisRoute
  '/panel/mesaj': typeof PanelMesajRoute
  '/panel/profil': typeof PanelProfilRoute
  '/panel/sifre': typeof PanelSifreRoute
  '/randevu/basarili': typeof RandevuBasariliRoute
  '/admin/': typeof AdminIndexRoute
  '/panel/': typeof PanelIndexRoute
  '/randevu/': typeof RandevuIndexRoute
  '/admin/danisan/$id': typeof AdminDanisanIdRoute
  '/admin/danisan/ekle': typeof AdminDanisanEkleRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/client/panel': typeof ApiV1ClientPanelRoute
  '/api/v1/staff/session': typeof ApiV1StaffSessionRoute
  '/api/v1/auth/admin/login': typeof ApiV1AuthAdminLoginRoute
  '/api/v1/auth/assistant/login': typeof ApiV1AuthAssistantLoginRoute
  '/api/v1/auth/client/login': typeof ApiV1AuthClientLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cikis': typeof CikisRoute
  '/cron': typeof CronRoute
  '/giris': typeof GirisRoute
  '/hakkimda': typeof HakkimdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/kvkk': typeof KvkkRoute
  '/sifremi-unuttum': typeof SifremiUnuttumRoute
  '/admin/asistan': typeof AdminAsistanRoute
  '/admin/bildirimler': typeof AdminBildirimlerRoute
  '/admin/danisanlar': typeof AdminDanisanlarRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/gorusler': typeof AdminGoruslerRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mali': typeof AdminMaliRoute
  '/admin/paketler': typeof AdminPaketlerRoute
  '/admin/randevular': typeof AdminRandevularRoute
  '/admin/sifreler': typeof AdminSifrelerRoute
  '/admin/tahliller': typeof AdminTahlillerRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/asistan/giris': typeof AsistanGirisRoute
  '/panel/mesaj': typeof PanelMesajRoute
  '/panel/profil': typeof PanelProfilRoute
  '/panel/sifre': typeof PanelSifreRoute
  '/randevu/basarili': typeof RandevuBasariliRoute
  '/admin': typeof AdminIndexRoute
  '/panel': typeof PanelIndexRoute
  '/randevu': typeof RandevuIndexRoute
  '/admin/danisan/$id': typeof AdminDanisanIdRoute
  '/admin/danisan/ekle': typeof AdminDanisanEkleRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/client/panel': typeof ApiV1ClientPanelRoute
  '/api/v1/staff/session': typeof ApiV1StaffSessionRoute
  '/api/v1/auth/admin/login': typeof ApiV1AuthAdminLoginRoute
  '/api/v1/auth/assistant/login': typeof ApiV1AuthAssistantLoginRoute
  '/api/v1/auth/client/login': typeof ApiV1AuthClientLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cikis': typeof CikisRoute
  '/cron': typeof CronRoute
  '/giris': typeof GirisRoute
  '/hakkimda': typeof HakkimdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/kvkk': typeof KvkkRoute
  '/panel': typeof PanelRouteWithChildren
  '/randevu': typeof RandevuRouteWithChildren
  '/sifremi-unuttum': typeof SifremiUnuttumRoute
  '/admin/asistan': typeof AdminAsistanRoute
  '/admin/bildirimler': typeof AdminBildirimlerRoute
  '/admin/danisanlar': typeof AdminDanisanlarRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/gorusler': typeof AdminGoruslerRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mali': typeof AdminMaliRoute
  '/admin/paketler': typeof AdminPaketlerRoute
  '/admin/randevular': typeof AdminRandevularRoute
  '/admin/sifreler': typeof AdminSifrelerRoute
  '/admin/tahliller': typeof AdminTahlillerRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/asistan/giris': typeof AsistanGirisRoute
  '/panel/mesaj': typeof PanelMesajRoute
  '/panel/profil': typeof PanelProfilRoute
  '/panel/sifre': typeof PanelSifreRoute
  '/randevu/basarili': typeof RandevuBasariliRoute
  '/admin/': typeof AdminIndexRoute
  '/panel/': typeof PanelIndexRoute
  '/randevu/': typeof RandevuIndexRoute
  '/admin/danisan/$id': typeof AdminDanisanIdRoute
  '/admin/danisan/ekle': typeof AdminDanisanEkleRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/client/panel': typeof ApiV1ClientPanelRoute
  '/api/v1/staff/session': typeof ApiV1StaffSessionRoute
  '/api/v1/auth/admin/login': typeof ApiV1AuthAdminLoginRoute
  '/api/v1/auth/assistant/login': typeof ApiV1AuthAssistantLoginRoute
  '/api/v1/auth/client/login': typeof ApiV1AuthClientLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cikis'
    | '/cron'
    | '/giris'
    | '/hakkimda'
    | '/hizmetler'
    | '/iletisim'
    | '/kvkk'
    | '/panel'
    | '/randevu'
    | '/sifremi-unuttum'
    | '/admin/asistan'
    | '/admin/bildirimler'
    | '/admin/danisanlar'
    | '/admin/export'
    | '/admin/gorusler'
    | '/admin/login'
    | '/admin/mali'
    | '/admin/paketler'
    | '/admin/randevular'
    | '/admin/sifreler'
    | '/admin/tahliller'
    | '/admin/telegram'
    | '/asistan/giris'
    | '/panel/mesaj'
    | '/panel/profil'
    | '/panel/sifre'
    | '/randevu/basarili'
    | '/admin/'
    | '/panel/'
    | '/randevu/'
    | '/admin/danisan/$id'
    | '/admin/danisan/ekle'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/client/panel'
    | '/api/v1/staff/session'
    | '/api/v1/auth/admin/login'
    | '/api/v1/auth/assistant/login'
    | '/api/v1/auth/client/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cikis'
    | '/cron'
    | '/giris'
    | '/hakkimda'
    | '/hizmetler'
    | '/iletisim'
    | '/kvkk'
    | '/sifremi-unuttum'
    | '/admin/asistan'
    | '/admin/bildirimler'
    | '/admin/danisanlar'
    | '/admin/export'
    | '/admin/gorusler'
    | '/admin/login'
    | '/admin/mali'
    | '/admin/paketler'
    | '/admin/randevular'
    | '/admin/sifreler'
    | '/admin/tahliller'
    | '/admin/telegram'
    | '/asistan/giris'
    | '/panel/mesaj'
    | '/panel/profil'
    | '/panel/sifre'
    | '/randevu/basarili'
    | '/admin'
    | '/panel'
    | '/randevu'
    | '/admin/danisan/$id'
    | '/admin/danisan/ekle'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/client/panel'
    | '/api/v1/staff/session'
    | '/api/v1/auth/admin/login'
    | '/api/v1/auth/assistant/login'
    | '/api/v1/auth/client/login'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cikis'
    | '/cron'
    | '/giris'
    | '/hakkimda'
    | '/hizmetler'
    | '/iletisim'
    | '/kvkk'
    | '/panel'
    | '/randevu'
    | '/sifremi-unuttum'
    | '/admin/asistan'
    | '/admin/bildirimler'
    | '/admin/danisanlar'
    | '/admin/export'
    | '/admin/gorusler'
    | '/admin/login'
    | '/admin/mali'
    | '/admin/paketler'
    | '/admin/randevular'
    | '/admin/sifreler'
    | '/admin/tahliller'
    | '/admin/telegram'
    | '/asistan/giris'
    | '/panel/mesaj'
    | '/panel/profil'
    | '/panel/sifre'
    | '/randevu/basarili'
    | '/admin/'
    | '/panel/'
    | '/randevu/'
    | '/admin/danisan/$id'
    | '/admin/danisan/ekle'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/client/panel'
    | '/api/v1/staff/session'
    | '/api/v1/auth/admin/login'
    | '/api/v1/auth/assistant/login'
    | '/api/v1/auth/client/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CikisRoute: typeof CikisRoute
  CronRoute: typeof CronRoute
  GirisRoute: typeof GirisRoute
  HakkimdaRoute: typeof HakkimdaRoute
  HizmetlerRoute: typeof HizmetlerRoute
  IletisimRoute: typeof IletisimRoute
  KvkkRoute: typeof KvkkRoute
  PanelRoute: typeof PanelRouteWithChildren
  RandevuRoute: typeof RandevuRouteWithChildren
  SifremiUnuttumRoute: typeof SifremiUnuttumRoute
  AsistanGirisRoute: typeof AsistanGirisRoute
  ApiV1AuthLogoutRoute: typeof ApiV1AuthLogoutRoute
  ApiV1AuthMeRoute: typeof ApiV1AuthMeRoute
  ApiV1ClientPanelRoute: typeof ApiV1ClientPanelRoute
  ApiV1StaffSessionRoute: typeof ApiV1StaffSessionRoute
  ApiV1AuthAdminLoginRoute: typeof ApiV1AuthAdminLoginRoute
  ApiV1AuthAssistantLoginRoute: typeof ApiV1AuthAssistantLoginRoute
  ApiV1AuthClientLoginRoute: typeof ApiV1AuthClientLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cikis': {
      id: '/cikis'
      path: '/cikis'
      fullPath: '/cikis'
      preLoaderRoute: typeof CikisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimda': {
      id: '/hakkimda'
      path: '/hakkimda'
      fullPath: '/hakkimda'
      preLoaderRoute: typeof HakkimdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetler': {
      id: '/hizmetler'
      path: '/hizmetler'
      fullPath: '/hizmetler'
      preLoaderRoute: typeof HizmetlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/randevu': {
      id: '/randevu'
      path: '/randevu'
      fullPath: '/randevu'
      preLoaderRoute: typeof RandevuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sifremi-unuttum': {
      id: '/sifremi-unuttum'
      path: '/sifremi-unuttum'
      fullPath: '/sifremi-unuttum'
      preLoaderRoute: typeof SifremiUnuttumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/asistan': {
      id: '/admin/asistan'
      path: '/asistan'
      fullPath: '/admin/asistan'
      preLoaderRoute: typeof AdminAsistanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bildirimler': {
      id: '/admin/bildirimler'
      path: '/bildirimler'
      fullPath: '/admin/bildirimler'
      preLoaderRoute: typeof AdminBildirimlerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/danisanlar': {
      id: '/admin/danisanlar'
      path: '/danisanlar'
      fullPath: '/admin/danisanlar'
      preLoaderRoute: typeof AdminDanisanlarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gorusler': {
      id: '/admin/gorusler'
      path: '/gorusler'
      fullPath: '/admin/gorusler'
      preLoaderRoute: typeof AdminGoruslerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mali': {
      id: '/admin/mali'
      path: '/mali'
      fullPath: '/admin/mali'
      preLoaderRoute: typeof AdminMaliRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paketler': {
      id: '/admin/paketler'
      path: '/paketler'
      fullPath: '/admin/paketler'
      preLoaderRoute: typeof AdminPaketlerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/randevular': {
      id: '/admin/randevular'
      path: '/randevular'
      fullPath: '/admin/randevular'
      preLoaderRoute: typeof AdminRandevularRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sifreler': {
      id: '/admin/sifreler'
      path: '/sifreler'
      fullPath: '/admin/sifreler'
      preLoaderRoute: typeof AdminSifrelerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tahliller': {
      id: '/admin/tahliller'
      path: '/tahliller'
      fullPath: '/admin/tahliller'
      preLoaderRoute: typeof AdminTahlillerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/telegram': {
      id: '/admin/telegram'
      path: '/telegram'
      fullPath: '/admin/telegram'
      preLoaderRoute: typeof AdminTelegramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/asistan/giris': {
      id: '/asistan/giris'
      path: '/asistan/giris'
      fullPath: '/asistan/giris'
      preLoaderRoute: typeof AsistanGirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/mesaj': {
      id: '/panel/mesaj'
      path: '/mesaj'
      fullPath: '/panel/mesaj'
      preLoaderRoute: typeof PanelMesajRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/profil': {
      id: '/panel/profil'
      path: '/profil'
      fullPath: '/panel/profil'
      preLoaderRoute: typeof PanelProfilRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/sifre': {
      id: '/panel/sifre'
      path: '/sifre'
      fullPath: '/panel/sifre'
      preLoaderRoute: typeof PanelSifreRouteImport
      parentRoute: typeof PanelRoute
    }
    '/randevu/': {
      id: '/randevu/'
      path: '/'
      fullPath: '/randevu/'
      preLoaderRoute: typeof RandevuIndexRouteImport
      parentRoute: typeof RandevuRoute
    }
    '/randevu/basarili': {
      id: '/randevu/basarili'
      path: '/basarili'
      fullPath: '/randevu/basarili'
      preLoaderRoute: typeof RandevuBasariliRouteImport
      parentRoute: typeof RandevuRoute
    }
    '/admin/danisan/$id': {
      id: '/admin/danisan/$id'
      path: '/danisan/$id'
      fullPath: '/admin/danisan/$id'
      preLoaderRoute: typeof AdminDanisanIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/danisan/ekle': {
      id: '/admin/danisan/ekle'
      path: '/danisan/ekle'
      fullPath: '/admin/danisan/ekle'
      preLoaderRoute: typeof AdminDanisanEkleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/v1/auth/logout': {
      id: '/api/v1/auth/logout'
      path: '/api/v1/auth/logout'
      fullPath: '/api/v1/auth/logout'
      preLoaderRoute: typeof ApiV1AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/me': {
      id: '/api/v1/auth/me'
      path: '/api/v1/auth/me'
      fullPath: '/api/v1/auth/me'
      preLoaderRoute: typeof ApiV1AuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/client/panel': {
      id: '/api/v1/client/panel'
      path: '/api/v1/client/panel'
      fullPath: '/api/v1/client/panel'
      preLoaderRoute: typeof ApiV1ClientPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/session': {
      id: '/api/v1/staff/session'
      path: '/api/v1/staff/session'
      fullPath: '/api/v1/staff/session'
      preLoaderRoute: typeof ApiV1StaffSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/admin/login': {
      id: '/api/v1/auth/admin/login'
      path: '/api/v1/auth/admin/login'
      fullPath: '/api/v1/auth/admin/login'
      preLoaderRoute: typeof ApiV1AuthAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/assistant/login': {
      id: '/api/v1/auth/assistant/login'
      path: '/api/v1/auth/assistant/login'
      fullPath: '/api/v1/auth/assistant/login'
      preLoaderRoute: typeof ApiV1AuthAssistantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/client/login': {
      id: '/api/v1/auth/client/login'
      path: '/api/v1/auth/client/login'
      fullPath: '/api/v1/auth/client/login'
      preLoaderRoute: typeof ApiV1AuthClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAsistanRoute: typeof AdminAsistanRoute
  AdminBildirimlerRoute: typeof AdminBildirimlerRoute
  AdminDanisanlarRoute: typeof AdminDanisanlarRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminGoruslerRoute: typeof AdminGoruslerRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMaliRoute: typeof AdminMaliRoute
  AdminPaketlerRoute: typeof AdminPaketlerRoute
  AdminRandevularRoute: typeof AdminRandevularRoute
  AdminSifrelerRoute: typeof AdminSifrelerRoute
  AdminTahlillerRoute: typeof AdminTahlillerRoute
  AdminTelegramRoute: typeof AdminTelegramRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDanisanIdRoute: typeof AdminDanisanIdRoute
  AdminDanisanEkleRoute: typeof AdminDanisanEkleRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAsistanRoute: AdminAsistanRoute,
  AdminBildirimlerRoute: AdminBildirimlerRoute,
  AdminDanisanlarRoute: AdminDanisanlarRoute,
  AdminExportRoute: AdminExportRoute,
  AdminGoruslerRoute: AdminGoruslerRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMaliRoute: AdminMaliRoute,
  AdminPaketlerRoute: AdminPaketlerRoute,
  AdminRandevularRoute: AdminRandevularRoute,
  AdminSifrelerRoute: AdminSifrelerRoute,
  AdminTahlillerRoute: AdminTahlillerRoute,
  AdminTelegramRoute: AdminTelegramRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDanisanIdRoute: AdminDanisanIdRoute,
  AdminDanisanEkleRoute: AdminDanisanEkleRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PanelRouteChildren {
  PanelMesajRoute: typeof PanelMesajRoute
  PanelProfilRoute: typeof PanelProfilRoute
  PanelSifreRoute: typeof PanelSifreRoute
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelMesajRoute: PanelMesajRoute,
  PanelProfilRoute: PanelProfilRoute,
  PanelSifreRoute: PanelSifreRoute,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

interface RandevuRouteChildren {
  RandevuBasariliRoute: typeof RandevuBasariliRoute
  RandevuIndexRoute: typeof RandevuIndexRoute
}

const RandevuRouteChildren: RandevuRouteChildren = {
  RandevuBasariliRoute: RandevuBasariliRoute,
  RandevuIndexRoute: RandevuIndexRoute,
}

const RandevuRouteWithChildren =
  RandevuRoute._addFileChildren(RandevuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CikisRoute: CikisRoute,
  CronRoute: CronRoute,
  GirisRoute: GirisRoute,
  HakkimdaRoute: HakkimdaRoute,
  HizmetlerRoute: HizmetlerRoute,
  IletisimRoute: IletisimRoute,
  KvkkRoute: KvkkRoute,
  PanelRoute: PanelRouteWithChildren,
  RandevuRoute: RandevuRouteWithChildren,
  SifremiUnuttumRoute: SifremiUnuttumRoute,
  AsistanGirisRoute: AsistanGirisRoute,
  ApiV1AuthLogoutRoute: ApiV1AuthLogoutRoute,
  ApiV1AuthMeRoute: ApiV1AuthMeRoute,
  ApiV1ClientPanelRoute: ApiV1ClientPanelRoute,
  ApiV1StaffSessionRoute: ApiV1StaffSessionRoute,
  ApiV1AuthAdminLoginRoute: ApiV1AuthAdminLoginRoute,
  ApiV1AuthAssistantLoginRoute: ApiV1AuthAssistantLoginRoute,
  ApiV1AuthClientLoginRoute: ApiV1AuthClientLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
